---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secret.sops.yaml
  - ./pvc.yaml
  - ./torrent/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./unpackerr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./autobrr/ks.yaml
  - ./traktarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./readarr/ks.yaml
  - ./calibre/ks.yaml
  - ./calibre-web/ks.yaml
  - ./jellystat/ks.yaml
  - ./huntarr/ks.yaml
