---
#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s
#

# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: "v1.33.1+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_debug: false
k3s_etcd_datastore: true
k3s_use_unsupported_config: true
k3s_registration_address: "{{ kube_vip_addr }}"
kubevip_address: "{{ kube_vip_addr }}"
k3s_server_manifests_urls:
  # Kube-vip
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml
  # Tigera Operator
  # https://github.com/projectcalico/calico/issues/7003
  - url: https://raw.githubusercontent.com/projectcalico/calico/v3.24.2/manifests/tigera-operator.yaml
    filename: tigera-operator.yaml
  # Prometheus Operator
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
    filename: alertmanagerconfigs.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
    filename: alertmanagers.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    filename: podmonitors.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
    filename: probes.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
    filename: prometheuses.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    filename: prometheusrules.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    filename: servicemonitors.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
    filename: thanosrulers.yaml
# (list) A flat list of templates to deploy on the primary control plane
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - calico-installation.yaml.j2
  - kube-vip-daemonset.yaml.j2

fedora:
  packages:
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - intel-gpu-tools
    - ipvsadm
    - lm_sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-pyyaml

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
    - autofs
