---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  KUBE_VIP_ADDR: "192.168.1.155"
  METALLB_LB_RANGE: "192.168.1.70-192.168.1.99"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.70"
  METALLB_EXTERNAL_INGRESS_ADDR: "192.168.1.71"
  METALLB_INTERNAL_INGRESS_ADDR: "192.168.1.81"
  ADGUARD_ADDR_NS1: "192.168.1.72"
  K8S_CLUSTER_CIDR: "10.42.0.0/16"
  K8S_SERVICE_CIDR: "10.43.0.0/16"
  SERVER_CIDR: "192.168.0.0/16"
  NFS_SERVER_IP: "192.168.1.200"
