---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./local-path-provisioner/ks.yaml
  - ./pvc.yaml
  - ./postgresql/ks.yaml
  - ./postgresql-17/ks.yaml
  - ./pgadmin/ks.yaml
  - ./redis/ks.yaml
  - ./minio/ks.yaml
  - ./synology/ks.yaml
  - ./emqx/ks.yaml
